### ISSUE TITLE
derlerken kullanılan versiyon bilgilerinin eklenmesi faydalı olabilir.

### ISSUE THREAD

**Issue by omerguzelelectronicguy** [farukyld/riscv-baremetal-benchmark#3]

**Comment by farukyld** [comment]
derleyici versiyonu, derleyicinin build'lendiği konfigürasyon ve spike versiyonu mu? @omerguzelelectronicguy

**Comment by omerguzelelectronicguy** [comment]
evet

**Comment by farukyld** [comment]
hocam [README.md](https://github.com/farukyld/riscv-baremetal-benchmark/blob/main/README.md)'nin yeni versiyonu size göre de tamamsa kapatabiliriz burayı

**Comment by omerguzelelectronicguy** [comment]
Eline sağlık
