### ISSUE TITLE
başlangıç adresleri ve boyut hakkında

### ISSUE THREAD

**Issue by omerguzelelectronicguy** [farukyld/riscv-baremetal-benchmark#4]
Programın girişi  başlangıcın 0x80 ilerisi bu sorun oluşturuyor. boot pc'yi buna ayarlamak bizim ortamımızda uğraştırıcı. Bu kondua değişiklik yapılabilir mi bakabilir misin?

Ayrıca programın boyutu ve load store yaptığı noktalar çok ileride. Bu da simülasyonda sorun oluşturuyor. bunu kısaltmamız mümkün mü?

**Comment by farukyld** [comment]
> Programın girişi başlangıcın 0x80 ilerisi bu sorun oluşturuyor. boot pc'yi buna ayarlamak bizim ortamımızda uğraştırıcı. Bu kondua değişiklik yapılabilir mi bakabilir misin?
Tammamdır. 
>Ayrıca programın boyutu ve load store yaptığı noktalar çok ileride. Bu da simülasyonda sorun oluşturuyor. bunu kısaltmamız mümkün mü?
stack'i programın önüne alıp heap'i en sona atıyoruz.

**Comment by omerguzelelectronicguy** [comment]
önüne mi sonuna mı? yani programdan sonra değil mi stack?

**Comment by farukyld** [comment]
program->stack->heap şeklinde

**Comment by farukyld** [comment]
burası da tamam
